package handler.command.impl.stream;

import domain.CacheDto;
import domain.StreamDto;
import enums.ValueType;
import handler.command.impl.TestHelper;
import org.junit.jupiter.api.*;
import service.RedisLocalMap;

import java.net.Socket;
import java.util.List;

import static org.junit.jupiter.api.Assertions.*;

/**
 * Unit tests for XAddHandler
 * 
 * Tests cover:
 * - XADD with explicit ID
 * - XADD with auto-generated ID (*)
 * - XADD with partial auto-generated ID (*-*)
 * - XADD validation (0-0 not allowed)
 * - XADD validation (ID must be greater than previous)
 * - TYPE on stream key returns "stream"
 */
@DisplayName("XAddHandler Tests")
class XAddHandlerTest {

    private XAddHandler xAddHandler;
    private Socket testSocket;

    @BeforeEach
    void setUp() {
        xAddHandler = new XAddHandler();
        xAddHandler.register();
        testSocket = TestHelper.createTestSocket();
        
        RedisLocalMap.LOCAL_MAP.clear();
    }

    @AfterEach
    void tearDown() {
        RedisLocalMap.LOCAL_MAP.clear();
    }

    @Test
    @DisplayName("XADD stream_key 0-1 foo bar should return '0-1'")
    void testXAddWithExplicitId() {
        String result = xAddHandler.process(testSocket, List.of("stream_key", "0-1", "foo", "bar"));
        
        assertEquals("$3\r\n0-1\r\n", result);
    }

    @Test
    @DisplayName("XADD should create stream with correct type")
    void testXAddCreatesStreamType() {
        xAddHandler.process(testSocket, List.of("stream_key", "0-1", "foo", "bar"));
        
        CacheDto cache = RedisLocalMap.LOCAL_MAP.get("stream_key");
        assertNotNull(cache);
        assertEquals(ValueType.STREAM, cache.getValueType());
        assertTrue(cache.getValue() instanceof StreamDto);
    }

    @Test
    @DisplayName("XADD with auto-generated ID (*) should work")
    void testXAddWithAutoGeneratedId() {
        String result = xAddHandler.process(testSocket, List.of("stream_key", "*", "foo", "bar"));
        
        assertTrue(result.startsWith("$"));
        assertTrue(result.contains("-"));
        assertTrue(result.endsWith("\r\n"));
    }

    @Test
    @DisplayName("XADD with partial auto-generated ID (0-*) should work")
    void testXAddWithPartialAutoGeneratedId() {
        String result = xAddHandler.process(testSocket, List.of("stream_key", "0-*", "foo", "bar"));
        
        // Should generate 0-1 for first entry with time part 0
        assertEquals("$3\r\n0-1\r\n", result);
    }

    @Test
    @DisplayName("XADD with ID 0-0 should return error")
    void testXAddWithZeroId() {
        String result = xAddHandler.process(testSocket, List.of("stream_key", "0-0", "foo", "bar"));
        
        assertTrue(result.contains("ERR"));
        assertTrue(result.contains("greater than 0-0"));
    }

    @Test
    @DisplayName("XADD with smaller ID than existing should return error")
    void testXAddWithSmallerId() {
        // First add
        xAddHandler.process(testSocket, List.of("stream_key", "1-1", "foo", "bar"));
        
        // Try to add with smaller ID
        String result = xAddHandler.process(testSocket, List.of("stream_key", "0-1", "foo", "bar"));
        
        assertTrue(result.contains("ERR"));
        assertTrue(result.contains("equal or smaller"));
    }

    @Test
    @DisplayName("XADD with equal ID should return error")
    void testXAddWithEqualId() {
        // First add
        xAddHandler.process(testSocket, List.of("stream_key", "1-1", "foo", "bar"));
        
        // Try to add with same ID
        String result = xAddHandler.process(testSocket, List.of("stream_key", "1-1", "foo", "bar"));
        
        assertTrue(result.contains("ERR"));
        assertTrue(result.contains("equal or smaller"));
    }

    @Test
    @DisplayName("XADD with null list should throw exception")
    void testXAddWithNullList() {
        assertThrows(RuntimeException.class, () -> {
            xAddHandler.process(testSocket, null);
        });
    }

    @Test
    @DisplayName("XADD with insufficient params should throw exception")
    void testXAddWithInsufficientParams() {
        assertThrows(RuntimeException.class, () -> {
            xAddHandler.process(testSocket, List.of("stream_key"));
        });
    }

    @Test
    @DisplayName("Multiple XADD operations should store entries in order")
    void testMultipleXAddOperations() {
        xAddHandler.process(testSocket, List.of("stream_key", "1-0", "a", "1"));
        xAddHandler.process(testSocket, List.of("stream_key", "2-0", "b", "2"));
        xAddHandler.process(testSocket, List.of("stream_key", "3-0", "c", "3"));
        
        CacheDto cache = RedisLocalMap.LOCAL_MAP.get("stream_key");
        StreamDto streamDto = (StreamDto) cache.getValue();
        assertEquals(3, streamDto.getStreamList().size());
        assertEquals("1-0", streamDto.getStreamList().get(0).getId());
        assertEquals("2-0", streamDto.getStreamList().get(1).getId());
        assertEquals("3-0", streamDto.getStreamList().get(2).getId());
    }

    @Test
    @DisplayName("XADD handler should be registered correctly")
    void testHandlerRegistration() {
        assertTrue(handler.command.CommandHandler.HANDLER_MAP.containsKey("xadd"));
        assertSame(xAddHandler, handler.command.CommandHandler.HANDLER_MAP.get("xadd"));
    }

    @Test
    @DisplayName("XADD with multiple key-value pairs")
    void testXAddWithMultipleKeyValuePairs() {
        String result = xAddHandler.process(testSocket, 
            List.of("stream_key", "1-0", "field1", "value1", "field2", "value2"));
        
        assertEquals("$3\r\n1-0\r\n", result);
        
        CacheDto cache = RedisLocalMap.LOCAL_MAP.get("stream_key");
        StreamDto streamDto = (StreamDto) cache.getValue();
        StreamDto.EntryDto entry = streamDto.getStreamList().get(0);
        assertEquals("value1", entry.getKvPair().get("field1"));
        assertEquals("value2", entry.getKvPair().get("field2"));
    }

    @Test
    @DisplayName("XADD with auto-increment sequence number for same timestamp")
    void testXAddAutoIncrementSequence() {
        xAddHandler.process(testSocket, List.of("stream_key", "1-0", "a", "1"));
        String result = xAddHandler.process(testSocket, List.of("stream_key", "1-*", "b", "2"));
        
        // Should auto-increment to 1-1
        assertEquals("$3\r\n1-1\r\n", result);
    }
}
